### ISSUE TITLE
不是Bug，想请教下如果要加PWA要怎么加啊

### ISSUE THREAD

**Issue by LiuYimin** [Yinzhuo19970516/vue-template#4]
如题。。

**Comment by Yinzhuo19970516** [comment]
对代码改造会比较多。之前设计的时候，没有考虑到这些。

看看这个？https://s.juejin.cn/ds/idc7rmyb/




尹卓_18811692101
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yinzhuo19970516/vue-template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月29日(星期天) 晚上10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Yinzhuo19970516/vue-template] 不是Bug，想请教下如果要加PWA要怎么加啊 (Issue #4)





 
如题。。

**Comment by LiuYimin** [comment]
谢谢
